### ISSUE TITLE
Can't start new project

### ISSUE THREAD

**Issue by Codi33** [mukezhz/geng#10]
Downloaded geng through go install and this error is showing when I'm creating new project.
![image](https://github.com/mukezhz/geng/assets/58087311/74dd3621-a8dd-4b2a-b976-5dba72d25ad3)

**Comment by mukezhz** [comment]
Hello @Codi33 sorry for late reply, I was busy in other work. I haven't test it in windows OS.

It seems like embedded file is not loading in your case.

Can you try building binary from source code?

**Comment by Codi33** [comment]
![scr](https://github.com/mukezhz/geng/assets/58087311/482057db-2126-447f-a6b4-4713bede779b)
The issue persists even with the binary compiled from the source code.

**Comment by mukezhz** [comment]
Hello @Codi33 , Thank you for the issue. I have resolved this issue.

The issue was due to filepath.Join.
Since I am using embedded file path, it seems to support only *nix path seperator.

Please install latest build and try again.
```
go install geng@latest
```

Let me know if it works or not.

Thank you!

🙇‍♂️

**Comment by Codi33** [comment]
Thank you for the update @mukezhz! I've installed the latest build and tried again. Everything seems to be working now.

**Comment by mukezhz** [comment]
@Codi33 Cool 

Let me know if you have any new idea for this project.

I will try to implement those.
